volumes:
  media:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pixel88art/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: pixel88art/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: pixel88art/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/mediafiles